<?php

/**
 * @file
 * Description.
 */

use Drupal\Core\Extension\ModuleHandlerInterface;

/**
 * Implements hook_library_info_alter().
 */
function dxpr_builder_simple_element_library_info_alter(array &$libraries, $extension) {
  if ($extension === 'dxpr_builder') {
    $module_handler = \Drupal::service('module_handler');
    $path = '/' . $module_handler->getModule('dxpr_builder_simple_element')->getPath() . '/js/';

    // Define the additional scripts to add.
    $additional_scripts = [
      'editor.builder' => [
        'dxpr_builder/dxpr_elements.js' => $path . 'simple_element.js',
      ],
      'development' => [
        'dxpr_builder/dxpr_elements.js' => $path . 'simple_element.js',
      ],
      'production' => [
        'dxpr_builder/dxpr_elements.js' => $path . 'simple_element.min.js',
      ],
    ];

    // Iterate over the defined additional scripts and add them to the library.
    foreach ($additional_scripts as $library_key => $scripts) {
      if (isset($libraries[$library_key]['js'])) {
        foreach ($scripts as $original_key => $script_path) {
          // Check if the original script exists in the library.
          if (array_key_exists($original_key, $libraries[$library_key]['js'])) {
            // Append the new script after the original.
            $original_key_index = array_search($original_key, array_keys($libraries[$library_key]['js']));
            $position = $original_key_index !== false ? $original_key_index + 1 : null;

            if ($position !== null) {
              // Insert the new script into the array at the calculated position.
              $new_js = [
                $script_path => [
                  'weight' => -4,
                  'minified' => TRUE,
                ]
              ];
              $libraries[$library_key]['js'] = array_merge(
                array_slice($libraries[$library_key]['js'], 0, $position, true),
                $new_js,
                array_slice($libraries[$library_key]['js'], $position, null, true)
              );
            }
          }
        }
      }
    }
  }
}
